### ISSUE TITLE
Enable user to specify existing VPC and subnets

### ISSUE THREAD

**Issue by jebbens** [awslabs/LISA#134]
A customer needs to specify a preexisting VPC and subnets created by their agency's cloud hosting division - because they do not have permissions to create their own VPCs - so that they can deploy LISA into their managed account.

**Comment by estohlmann** [comment]
Hey @jebbens I reviewed the code and we do allow a user to specify an [existing vpcId](https://github.com/awslabs/LISA/blob/develop/lib/schema.ts#L834) in our configuration file, if this is present LISA will use the VPC and the subnets available in the VPC for deployment.

**Comment by perrojo** [comment]
Hey @estohlmann While you're able to specify a VPC using the config file, in some instances CDK selects certain types of subnets only. For example a VPC with only "Isolated" subnets will cause the deployment to not even start. The ideal fix here would be allowing users to provide an array of subnet ids with the current VPC id config.

**Comment by estohlmann** [comment]
Hey @perrojo and @jebbens - Thank you for the feedback. We are looking to address this in our next release! I will keep you updated here as we get this added to the baseline.

**Comment by estohlmann** [comment]
Hey @perrojo and @jebbens - this was addressed in the following PR: https://github.com/awslabs/LISA/pull/155.

Please reopen and let us know if you have any issues.
