### ISSUE TITLE
Enable user to specify existing security groups

### ISSUE THREAD

**Issue by jebbens** [awslabs/LISA#135]
A customer needs to specify preexisting security groups created by their agency's cloud hosting division - because they do not have permissions to create their own SGs - so that they can deploy LISA into their managed account.

**Comment by estohlmann** [comment]
Hey @jebbens, thank you for bringing this to our attention! We will review this PFR for potential inclusion in our next release. I will keep you up to date here!

**Comment by estohlmann** [comment]
This was resolved today and will go to LISA version 3.3.0
