### ISSUE TITLE
Enable user to specify a private endpoint type

### ISSUE THREAD

**Issue by jebbens** [awslabs/LISA#137]
A customer needs to specify a the API Gateway endpoint type so that they meet security requirements from their sponsor agency's cloud hosting division to deploy LISA into their managed account.

**Comment by estohlmann** [comment]
Hey @jebbens, thank you for bringing this to our attention! We will review this PFR for potential inclusion in our next release. I will keep you up to date here!

**Comment by estohlmann** [comment]
Hey @jebbens - this was addressed in the following PR: https://github.com/awslabs/LISA/pull/153.

Please reopen and let us know if you have any issues.
