### ISSUE TITLE
Enable user to specify IAM roles

### ISSUE THREAD

**Issue by jebbens** [awslabs/LISA#138]
A customer needs to specify preexisting IAM roles - because they do not have permissions to create IAM and application resources with the same roles - so that they can deploy LISA into their managed account.

**Comment by estohlmann** [comment]
Hey @jebbens, thank you for bringing this to our attention! We will review this PFR for potential inclusion in our next release. I will keep you up to date here!

**Comment by estohlmann** [comment]
Hey there @jebbens - This was resolved with this [PR](https://github.com/awslabs/LISA/pull/172) and will be included in our next release. Thanks!
