### ISSUE TITLE
No match for platform in manifest when deploying LisaServeIAMStack

### ISSUE THREAD

**Issue by david-saeger** [awslabs/LISA#43]
Im fairly new to LISA so not convinced this isnt user error of some sort.. 

My first deploy of LISA keeps erroring out during the LisaServeIAMStack deployment with the error 

```
 > [internal] load metadata for ghcr.io/huggingface/text-generation-inference:2.0.1:

#3 ERROR: no match for platform in manifest sha256:cabd2a49a3afa7106aaa0bb3458c11904007fcd0369a83fcc1fa2fab76d444b4: not found
```

Some further context:

- The environment is gov cloud.
- I skipped the local generation of safe tensors as all the models I am using have those pre generated in hugging face.

Happy to provide any other context that would be useful.

**Comment by krzim-aws** [comment]
Hi @david-saeger, what machine are you deploying from? My hunch is that you're on an ARM based Mac?

If so, the issue stems from the fact that TGI only provides images built for x86_64 (the arch of our EC2 targets as well) but your local docker is configured to pull ARM based images for use on a Mac.

You may have luck running `export DOCKER_DEFAULT_PLATFORM=linux/amd64` as a part of your environment setup. I (and most others) have the most success deploying LISA from Amazon Linux instances in EC2/SageMakerNotebook/Cloud9 etc. but I'm interested in learning about how you are deploying the solution.

**Comment by david-saeger** [comment]
@krzim-aws you are right on all accounts. Was attempting deploy from a Mac M1. exporting the docker platform environment did enable successful deployment. Going to close this ticket out. Thanks 😄 !

**Comment by krzim-aws** [comment]
Awesome! Glad to hear that resolved your issue. @petermuller we might consider adding this to the documentation?

**Comment by david-saeger** [comment]
reopening as I think building docker images for the linux/amd64 had further downstream effects. I was able to deploy many of the stacks but ECS containers all fail with 
```
exec ./src/entrypoint.sh: exec format error
```
on startup I suppose this is because the docker image 

I take it these are related 

https://stackoverflow.com/questions/74705475/aws-ecs-exec-usr-local-bin-docker-entrypoint-sh-exec-format-error

Not sure if it is possible or worth the effort for the images to be platform independent but that would likely reduce some of this friction.

**Comment by krzim-aws** [comment]
That error is indeed because the images were built for the wrong architecture. I think we'll need to go one step further here to ensure that all of the ARM based images are destroyed and rebuilt. 

Can you please remove all of the CDK generated images from your local docker registry, run a docker prune to remove the build cache, and then rerun? If the error persists, then we know this solution isn't the answer.

Example commands to remove all images (not just the CDK generated ones) and do a system prune (removes all unused volumes, containers, images, caches, .etc) would look like :
```bash
docker rmi -f $(docker images -aq)
docker system prune
```

**Comment by david-saeger** [comment]
hmm yea cleaned up the CDK generated images and attempted re deploy with no joy 

```
The stack named owl-owl-serve-dev failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Error occurred during operation 'ECS Deployment Circuit Breaker was triggered'." (RequestToken: 3c4545df-a590-979b-b340-a6dbb26818db, HandlerErrorCode: GeneralServiceException)
    at FullCloudFormationDeployment.monitorDeployment (/Users/dsaeger/projects/LISA/node_modules/aws-cdk/lib/index.js:428:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/dsaeger/projects/LISA/node_modules/aws-cdk/lib/index.js:431:182776)
    at async /Users/dsaeger/projects/LISA/node_modules/aws-cdk/lib/index.js:431:164745
```

**Comment by david-saeger** [comment]
some context that I assumed would not be relevant but figure I might as well share just in case is that I was running into timeouts generating safetensors so I downloaded those artifacts from hugging face and manually uploaded them to the s3 bucket. Curious if this might be tripping things up somehow.

**Comment by krzim-aws** [comment]
That shouldn't be an issue. There could be yet one more place that the old docker images are hiding. Can you delete the local images as well as any CDK generated images for this deployment in ECR in the AWS console as well?

Unfortunately I don't have an exact setup to replicate this on my end. The other option (and the most well tested) is to do a deployment from an EC2 instance or even SageMaker Notebook if you have access to one.

**Comment by david-saeger** [comment]
Thanks for this iterating on error messages so that is promising to some degree. Still erroring out on deploying LisaServe but now I'm getting 
```
"Group did not stabilize. Last scaling activity: The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed."
```

[documentation](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ts-as-instancelaunchfailure.html#ts-as-instancelaunchfailure-3) indicates that this may be the result of "instance configuration might not be supported in your requested AWS Region or Availability Zones." it seems the requested instance type is available in my region so perhaps there is something about its configuration that is particular to our deployment environment. Dont think its a VPC setup thing because we deviate from the LISA vpc deployment

**Comment by david-saeger** [comment]
I think the AWS environment I am attempting to deploy to does not allow for an ECS AMI to match the `AmiHardwareType.GPU`

**Comment by petermuller** [comment]
Thanks for your help @krzim-aws !

@david-saeger which region and instance type do you have configured? If there was an instance launch failure, it could possibly be because the instance isn't available in that particular region. Possibly a different instance type could help there?

Which ASG failed to stabilize? Was that the REST API ASG or was that one of the model ASGs?

**Comment by david-saeger** [comment]
Yes thanks so much @krzim-aws for all your help. I am working out of `us-gov-west-1` and an instance type of m5.large which according to [these docs](https://docs.aws.amazon.com/ec2/latest/instancetypes/ec2-instance-regions.html#instance-types-us-gov-west-1) should not present an incompatibility. This made me think that the issue could be stemming from a mismatch in the hardware type requested. I did notice a difference in the AMI's available across commercial and gov-cloud accounts which led me to this belief.

**Comment by petermuller** [comment]
Based on the M5- i'm assuming that it's the REST API ASG that's failing? Otherwise if it's one of the model ASGs that's failing, I think us-gov-west-1 does not have the G5 instances that are selected by default in our Mistral example. Do you have a logical ID from CloudFormation for which resource failed? I also suspect that the M5's are not the problem.

**Comment by david-saeger** [comment]
No worries this is really helpful!! I do have access to cloudformation The logical ID for the rolledback stack is `owl-owl-serve-dev` (owl being the name I am giving to the thing) then there are a lot of deleted resources in that stack that all have logical ids so not sure which to report back. Is that useful info? Should I try to re-run?

**Comment by petermuller** [comment]
That's the overall stack name, but there should be a  morespecific resource that gets the circuit breaker message as the status reason. If you go into the stack events for that deleted stack, you should be able to find the specific resource that has the "circuit breaker" message as the failure code in the status reason column. The logical resource should probably have "ASG" in the name, and the resource type will be "AWS::AutoScaling::AutoScalingGroup".

**Comment by david-saeger** [comment]
Got it. Thanks for baby stepping me through this, still getting my feet wet with cloud formation. Looks like I got a create failed on  logical ID's `mistral7bEcsModelECCmistral7bClmistral7bASGD2028F30` and `e5v2EcsModelECCe5v2Cle5v2ASGBA51EA33` and those led to the rollback.

**Comment by krzim-aws** [comment]
Ah there's a decent chance those won't be able to be deployed on non-GPU enabled instances like the m5. Your best bet would be to try a g4dn.2xlarge for the mistral model and a g4dn.xlarge for the e5 model.

**Comment by david-saeger** [comment]
Hmm tried deploying with the instances specified here but they triggered the circuit breaker at the same place .. logical IDs `mistral7bEcsModelECCmistral7bEc2SvcService64B3C597` and `e5v2EcsModelECCe5v2Ec2SvcService1B59654D`

**Comment by petermuller** [comment]
I see- In that case, are you able to pull up any of the ECS-related logs? There may be a few different log groups now because of multiple failed deployments, but you can get logs in the related ECS service logs in CloudWatch logs with "ContainerLogGroup" in the log group name. So for instance, one of mine looks like: "peter-lisa-serve-dev-e5embeddingteiEcsModelECCe5embeddingteiEc2TaskDefinitione5embeddingteiContainerLogGroup9B228B32-1P17Bt5jpdTO" (long name, but the log streams in here can give insight into why it failed). You log stream would look similar, with your deployment name at the beginning, and your model name somewhere in that long string. I suspect GPU-related issues based on instance types, but these will confirm for sure.

**Comment by david-saeger** [comment]
OK yeah nice.. Seeing logs come through now. 

minstal (g4dn.2xlarge) errored out with `Error: Warmup(Generation("CANCELLED"))` and `RuntimeError: CUDA error: no kernel image is available for execution on the device\nCUDA kernel`

e5-large-v2 (g4dn.xlarge) errored with `Could not start backend: Runtime compute cap 75 is not compatible with compile time compute cap 80`

**Comment by krzim-aws** [comment]
Ah there seems to be an issue with your deployed version of the TGI image running on the T4 (Turing arch/7.5 compute capability) cards on the g4dn instance. Can you change the image version to 2.0.4 in your config? It corresponds to [this line](https://github.com/awslabs/LISA/blob/1f783b68c99e2e3d1524c3fedb4f044959bd1f9e/example_config.yaml#L132) in the `example_config.yaml` file.

**Comment by david-saeger** [comment]
Just got serve-dev to deploy. bumping 2.0.4 got it through for Minstral but the e5-large-v2 embedding model needed a base image tagged with turing (used turing-latest) to successfully deploy. Haven't had time to look around much but progress is being made! Thanks much for your support so far and hope this exchange has some utility for the project.

**Comment by petermuller** [comment]
Awesome, glad to hear!

From this thread, we have a few actions items that I can see:
1. Documentation around deploying with an ARM Mac
2. Documentation on how to troubleshoot circuit breaker events
3. Supplementary information on GPU instances based on model type and error messaging.

Thanks for your patience in working with us @david-saeger and thanks for all your help @krzim-aws !

I'm going to close this issue now, but please reopen if it's the same thread of troubleshooting you need or please open a new issue if you find any new problems we need to address. Thanks!

**Comment by krzim-aws** [comment]
Glad you were able to get things up and running!

> e5-large-v2 embedding model needed a base image tagged with turing

Yes, good call on that! We hadn't discussed any failures with the e5 model but you need to specify the Turing version of the TEI image to run on the T4 cards on the g4dn instances. The `latest` tag should support Ampere, Hopper, and Ada Lovelace (p4, g5, g6, p5) out of the box.
