### ISSUE TITLE
Problems building v3

### ISSUE THREAD

**Issue by david-saeger** [awslabs/LISA#94]
Ive had a couple issues deploying on LISA v3 over the past couple days. 

Most recently after an attempt to start over (after destroying with `make destroy`) I am getting the following error `owl-owl-serve-dev:  fail: No ECR repository named 'cdk-hnb659fds-container-assets-189215246007-us-gov-west-1' in account 189215246007. Is this account bootstrapped?`

I can confirm that the account is bootstrapped but bootstrapping does not create an ECR repository. Should it? I can confirm that I attempted redeploying after deleting cloudformation stacks and cleaning up all local docker images.

**Comment by david-saeger** [comment]
I actually dont think that was the error that killed the build. it was 


```
Deployment failed: Error: Failed to build asset 88ce152917d42e7d2d5c42a3f26127b04437c42a55307203e1548bdd3e4c4d04:189215246007-us-gov-west-1
    at Deployments.buildSingleAsset (/Users/dsaeger/projects/LISA/node_modules/aws-cdk/lib/index.js:431:11312)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.buildAsset (/Users/dsaeger/projects/LISA/node_modules/aws-cdk/lib/index.js:431:180409)
    at async /Users/dsaeger/projects/LISA/node_modules/aws-cdk/lib/index.js:431:164798
```

I suspect there may be cross platform issues with the ecs_model_deployer

**Comment by petermuller** [comment]
Hi David, just wanted to confirm, was this resolved, or what did you do to fix the issue for yourself? Just want to make sure that we aren't missing any steps in the readme, or if we can make the steps more clear, we can do that too.

**Comment by david-saeger** [comment]
resolved! was able to deploy after deleting some legacy s3 buckets created in V2 deploy. I should have done a better job documenting my steps so forgetting which specific bucket got me over the line.

**Comment by petermuller** [comment]
No worries, thanks!
